#!/usr/bin/env python3
"""Initialize a memory bank folder structure."""

import sys
from pathlib import Path

MEMORY_DIR = Path("./memory")
FOLDERS = [
    "episodic",
    "semantic",
    "procedural",
    "archive",
    "summaries/episodic/weekly",
    "summaries/episodic/monthly",
]

INDEX_STARTER = """# Memory Index

> Auto-generated by `scripts/index.py`. Run it after creating or updating memories.

This folder is currently empty. Once you add memories, re-run the index script.

## Quick Start

1. Create a memory from a template in `skills/memory-bank/templates/`
2. Save it to `./memory/<type>/`
3. Run `python skills/memory-bank/scripts/index.py` to rebuild this file
"""


def main():
    if MEMORY_DIR.exists():
        print(f"Memory directory already exists at {MEMORY_DIR.resolve()}")
    else:
        MEMORY_DIR.mkdir(parents=True, exist_ok=True)
        print(f"Created {MEMORY_DIR.resolve()}")

    for folder in FOLDERS:
        sub = MEMORY_DIR / folder
        sub.mkdir(parents=True, exist_ok=True)
        print(f"  + {sub}")

    index_path = MEMORY_DIR / "INDEX.md"
    if not index_path.exists():
        index_path.write_text(INDEX_STARTER, encoding="utf-8")
        print(f"  + {index_path} (starter)")

    print("\nDone. Start creating memories, then run the index script to keep INDEX.md fresh.")


if __name__ == "__main__":
    main()
