#!/usr/bin/env python3
"""Hard rule: no relative paths in user-authored docs.

Walks every .md file under docs/ (recursively, EXCLUDING INDEX.md and
files under docs/changes/*/ that are siblings of the canonical change
artifacts), and reports any link path that is:

  - Not absolute (doesn't start with `/`)
  - Not an external URL (http://, https://, mailto:, tel:)
  - Not a pure anchor (#section)

This is the "no relative crap" rule, made enforceable. The intent is:
once an author migrates to the leading-/ absolute form, no future
commit should sneak `../` or `./` or bare `foo.md` back into docs/.

## Special cases (intentionally NOT enforced)

1. `INDEX.md` files — these are auto-generated by index.py. They use
   folder-relative paths internally, which is correct. We do NOT
   lint them.

2. `docs/changes/<name>/{proposal,behavior,design,tasks}.md` — the
   canonical change-artifact templates use bare-filename siblings
   (e.g. `[proposal.md]`) because the parent folder name is dynamic
   per change. The resolver handles this correctly. The rule is
   relaxed for this pattern only.

3. `skills/code-docs/refs/`, `skills/code-docs/templates/` — these
   are skill internals, not user docs. They use `../foo.md` for
   internal navigation. Out of scope.

## Usage

    python scripts/check-no-relative.py docs/                  # default: report, exit 1 on violations
    python scripts/check-no-relative.py docs/ --no-fail        # report only, exit 0
    python scripts/check-no-relative.py docs/ --verbose        # show every inspected file
    python scripts/check-no-relative.py docs/ --include-changes # also lint docs/changes/*/
                                                          # (default: skipped per special case 2)

Exit codes:
    0 — clean (or `--no-fail`)
    1 — violations found
    2 — wrong usage / missing folder
"""

import re
import sys
from pathlib import Path

from _ontology import (
    parse_frontmatter,
    find_project_root,
)


# Markdown link regex (same shape as status.py / migrate-links.py)
_LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")

# Top-level docs folder names (for sanity context, not gating)
_DOCS_TOP_LEVEL = frozenset({
    "overview", "spec", "specs", "architecture", "components",
    "decisions", "verification", "guides", "ops", "reference", "changes", "archive",
})

# Canonical change artifact filenames (sibling-relative is allowed inside a change folder)
_CHANGE_ARTIFACTS = frozenset({"proposal.md", "behavior.md", "design.md", "tasks.md"})


def is_violation(href: str) -> bool:
    """Return True if this href is a relative path that violates the no-relative rule."""
    if not href:
        return False
    lowered = href.lower()
    # External URLs are fine
    if "://" in lowered or lowered.startswith("mailto:") or lowered.startswith("tel:"):
        return False
    # Pure anchors are fine
    if href.startswith("#"):
        return False
    # Already absolute — that's the rule
    if href.startswith("/"):
        return False
    # Drop query/fragment for the path check
    clean = href.split("#", 1)[0].split("?", 1)[0]
    if not clean:
        return False
    # Anything else (../, ./, bare filename, folder/prefix.md) is a violation
    return True


def is_in_changes_folder(filepath: Path, docs_root: Path) -> bool:
    """True if filepath is inside docs/changes/<something>/."""
    try:
        rel = filepath.relative_to(docs_root)
    except ValueError:
        return False
    parts = rel.parts
    return len(parts) >= 2 and parts[0] == "changes"


def is_change_artifact(filepath: Path) -> bool:
    """True if filepath is one of the canonical change artifact names."""
    return filepath.name in _CHANGE_ARTIFACTS


def extract_frontmatter_hrefs(fm: dict) -> list[tuple[str, str]]:
    """Extract (link_type, href) pairs from frontmatter `links:` block.

    Also includes the `resource:` field if present.
    """
    out: list[tuple[str, str]] = []

    # resource: single string
    if "resource" in fm:
        val = fm["resource"]
        if isinstance(val, str):
            out.append(("resource", val))

    # links: dict of link_type → list of hrefs
    links = fm.get("links", {})
    if isinstance(links, dict):
        for link_type, targets in links.items():
            if isinstance(targets, str):
                targets = [targets]
            if not isinstance(targets, list):
                continue
            for t in targets:
                if isinstance(t, str):
                    out.append((link_type, t))
    return out


def extract_body_hrefs(text: str) -> list[str]:
    """Extract hrefs from inline markdown links in body text.

    Skips frontmatter and fenced code blocks.
    """
    if not text.startswith("---"):
        body = text
    else:
        parts = text.split("---", 2)
        if len(parts) < 3:
            return []
        body = parts[2]

    # Strip fenced code blocks
    out: list[str] = []
    in_fence = False
    fence_re = re.compile(r"^\s*```")
    for line in body.splitlines():
        if fence_re.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        for match in _LINK_RE.finditer(line):
            out.append(match.group(2).strip())
    return out


# ── Main ───────────────────────────────────────────────────────────


def main():
    if "--help" in sys.argv or "-h" in sys.argv:
        print(__doc__.strip())
        sys.exit(0)

    no_fail = "--no-fail" in sys.argv
    verbose = "--verbose" in sys.argv or "-v" in sys.argv
    include_changes = "--include-changes" in sys.argv

    args = [a for a in sys.argv[1:] if not a.startswith("--") and not a.startswith("-")]
    if args:
        root = Path(args[0]).resolve()
    else:
        script_dir = Path(__file__).resolve().parent
        project = find_project_root(script_dir)
        root = (project / "docs") if project else (Path.cwd() / "docs")

    if not root.exists():
        print(f"Error: {root} does not exist.")
        sys.exit(2)

    if not root.is_dir():
        print(f"Error: {root} is not a directory.")
        sys.exit(2)

    files_scanned = 0
    files_skipped = 0
    total_violations = 0
    by_type: dict[str, int] = {}

    # Walk all .md files
    for fp in sorted(root.rglob("*.md")):
        files_scanned += 1

        # Skip INDEX.md (auto-generated)
        if fp.name == "INDEX.md":
            files_skipped += 1
            if verbose:
                print(f"  ⏭  {fp.relative_to(root)}  (INDEX.md, auto-generated)")
            continue

        # Special case: docs/changes/*/canonical-artifact.md
        # The four canonical files inside a change folder are allowed
        # to use bare-filename siblings (e.g. [proposal.md]).
        if not include_changes and is_in_changes_folder(fp, root) and is_change_artifact(fp):
            files_skipped += 1
            if verbose:
                print(f"  ⏭  {fp.relative_to(root)}  (change artifact, sibling-relative allowed)")
            continue

        try:
            text = fp.read_text(encoding="utf-8")
        except Exception as e:
            print(f"  ⚠️  {fp.relative_to(root)}  could not read: {e}")
            continue

        fm = parse_frontmatter(text) or {}
        violations: list[tuple[str, str, str]] = []  # (location, link_type_or_kind, href)

        # Frontmatter `links:` and `resource:`
        for link_type, href in extract_frontmatter_hrefs(fm):
            if is_violation(href):
                violations.append(("frontmatter", link_type, href))

        # Body inline links
        for href in extract_body_hrefs(text):
            if is_violation(href):
                violations.append(("body", "inline", href))

        if not violations:
            if verbose:
                print(f"  ✓ {fp.relative_to(root)}")
            continue

        for location, link_type, href in violations:
            by_type[location] = by_type.get(location, 0) + 1
            total_violations += 1
            print(f"  ❌ {fp.relative_to(root)}")
            print(f"       {location}.{link_type}: {href}")

    # Summary
    print()
    print(f"  Files scanned: {files_scanned}  (skipped: {files_skipped})")
    if total_violations == 0:
        print(f"  ✅ No relative paths found. Docs are absolute-clean!")
    else:
        print(f"  ❌ {total_violations} relative path{'s' if total_violations > 1 else ''} found:")
        for loc, count in sorted(by_type.items()):
            print(f"       {loc}: {count}")
        print()
        print("  Fix: rewrite each path with a leading `/`.")
        print("       Run `python scripts/migrate-links.py <docs-path>` to auto-fix.")
    print()

    if total_violations > 0 and not no_fail:
        sys.exit(1)


if __name__ == "__main__":
    main()
